---
  - name: Setup sshd config
    ansible.builtin.copy:
       src: files/sshd_config
       dest: /etc/ssh/sshd_config
       mode: 644
    notify: Restart sshd

  - name: Check if net-tools is latest
    ansible.builtin.apt:
      name: net-tools
      state: latest
 
  - name: Check if git is latest
    ansible.builtin.apt:
      name: git
      state: latest
